master tx: add comm_master_tx function definition to the header file.
Phase green - make test pass.
To deal with implicit function declaration error, declared it in header
file. Also added missing headers for stdint types. Program still doesn't
compile because of undefined reference to 'comm_master_tx' error.